### ISSUE TITLE
Collection.AddIndex missing from Client and gRPC

### ISSUE THREAD

**Issue by asutula** [textileio/go-threads#290] opened 2020-03-27 20:38 UTC
Appears we never added it, we should. Without it, you can only define indexes when you create a collection.

**Comment by carsonfarmer** [comment] 2020-03-27 20:40
This was actually originally by design, because #286, so before we expose AddIndex via clients, we should probably get that implemented.

**Comment by asutula** [comment] 2020-03-27 20:50
I see. I've been thinking about the back-indexing and realizing how complex it is because the data is unbounded in size :(

**Comment by sanderpick** [comment] 2020-05-27 21:09
Closing as handled by `UpdateCollection`

**Closed by sanderpick** 2020-05-27 21:09 UTC
